### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by llmgpt** [Chemino/AI-Rex#2]
As a non-chemistry major, how can you understand your job? The usage of code is not mentioned either.

**Comment by oytang** [comment]
Hello @llmgpt , thank you for being interested in our project. This repo worked to develop a model to predict whether a chemical reaction is feasible or not, given the reactants and products. The usage of code is explained in each module of the repo, try looking into each directory. Currently, some READMEs are solely in SImplified Chinese, but I'll recommend using a DeepL translator or ChatGPT to translate them. Let us know if the translation quality is not satisfactory.
